# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Matrix Algebra with Computational Applications
author: Dirk Colbry
logo: Cover.jpg
copyright: '2021'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout : 30  
  stderr_output : remove
  
repository:
  url: https://github.com/colbrydi/MatrixAlgebra
  path_to_book: docs/_sources/  # An optional path to your book, defaults to repo root
  branch      : main 
html:
  use_issues_button: true
  use_repository_button: true
  #use_edit_page_button: true
  
launch_buttons:
  notebook_interface: "classic"  # or "jupyterlab"
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  #Add to docker file RUN pip install jupytext nbgitpuller
  #jupyterhub_url: "http://jupyterhub.egr.msu.edu/"
  
  binderhub_url                    : "https://mybinder.org"  # The URL for your BinderHub.
  binder_repo_base                 : "https://github.com/"  # The site on which the textbook repository is hosted
  binder_repo_org                  : "colbrydi"  # The username or organization that owns this repository
  binder_repo_name                 : "MatrixAlgebra"  # The name of the repository on the web
  binder_repo_branch               : "master"  # The branch on which your textbook is hosted.
