# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Matrix Algebra with Computational Applications
author: Dirk Colbry
logo: Cover.jpg
copyright: '2021'
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout : 30  
  stderr_output : remove
# repository:
#   url                       : ""  # The URL to your book's repository
#   path_to_book              : docs  # A path to your book's folder, relative to the repository root.
#   branch                    : master  # Which branch of the repository should be used when creating links
