channels:
  - defaults
dependencies:
  - jupyter
  - numpy
  - scipy
  - sympy
  - matplotlib
  - scikit-image
  - ipywidgets
  - pandas
  - pathlib
  - pip:
    - jupyter-book
    - git+https://github.com/colbrydi/jupyterinstruct   
