channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jupyter
  - numpy
  - scipy
  - sympy
  - matplotlib
  - scikit-image
  - ipywidgets
  - pandas
  - pathlib
  - jupytext
  - pip:
    - jupyter-book
    - git+https://github.com/colbrydi/jupyterinstruct   
